name: Localize New Pages

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      new_files: ${{ steps.detect_changes.outputs.new_files }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect new localized pages
      id: detect_changes
      run: |
        git config --global --add safe.directory /github/workspace
        NEW_FILES=$(git diff --name-status HEAD~1 HEAD | grep '^A' | awk '{print $2}')
        if [ -z "$NEW_FILES" ]; then
          echo "No new files detected."
        else
          echo "New files detected: $NEW_FILES"
          echo "new_files=$NEW_FILES" >> $GITHUB_OUTPUT
        fi

  localize:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.new_files != ''
    strategy:
      matrix:
        lang: ["fr", "it"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Translate new files
      uses: maibine/git_training/TranslateActionSolution@master
      with:
        openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        lang: ${{ matrix.lang }}
        input_dir: './docs'
        repo_dir: './'

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b "locale-${{ matrix.lang }}" || git checkout "locale-${{ matrix.lang }}"
        git pull origin "locale-${{ matrix.lang }}" --rebase
        git add "i18n/${{ matrix.lang }}/docusaurus-plugin-content-docs/current"
        git commit -m "Add new localized pages for ${{ matrix.lang }}"
        git push origin "locale-${{ matrix.lang }}"

    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: npm

    - name: Install Dependencies
      run: |
        npm install @octokit/rest esm
        npm audit fix
  
    - name: Create issues for translation review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW_FILES: ${{ needs.detect-changes.outputs.new_files }}
        LANG: ${{ matrix.lang }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      run: |
        node -r esm scripts/create-issue.js