name: Localize New Pages

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      new_files: ${{ steps.detect_changes.outputs.new_files }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect new localized pages
      id: detect_changes
      run: |
        git config --global --add safe.directory /github/workspace
        NEW_FILES=$(git diff --name-status HEAD~1 HEAD | grep '^A' | awk '{print $2}')
        if [ -z "$NEW_FILES" ]; then
          echo "No new files detected."
        else
          echo "New files detected: $NEW_FILES"
          echo "new_files=$NEW_FILES" >> $GITHUB_OUTPUT
        fi

  localize:
    needs: detect-changes
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: needs.detect-changes.outputs.new_files != ''
    strategy:
      matrix:
        lang: ["fr", "it"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Translate new files
      uses: maibine/git_training/TranslateActionSolution@master
      with:
        openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        lang: ${{ matrix.lang }}
        input_dir: './docs'
        repo_dir: './'

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b "locale-${{ matrix.lang }}" || git checkout "locale-${{ matrix.lang }}"
        git pull origin "locale-${{ matrix.lang }}" --rebase
        git add "i18n/${{ matrix.lang }}/docusaurus-plugin-content-docs/current"
        git commit -m "Add new localized pages for ${{ matrix.lang }}"
        git push origin "locale-${{ matrix.lang }}"

    - name: Create issues for translation review
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW_FILES: ${{ needs.detect-changes.outputs.new_files }}
        LANG: ${{ matrix.lang }}
      run: |
        new_files=$(echo $NEW_FILES | tr ' ' '\n')
        body="The following new pages need to be translated to $LANG:\n\n"
        for file in $new_files; do
        body+="- [ ] i18n/$LANG/docusaurus-plugin-content-docs/current/${file/docs\//}\n"
        done
        gh issue create \
        --title "Translate new pages to $LANG" \
        --assignee "Adi-Fluentis" \
        --label "translation" \
        --body "$body"