name: Automatic Translation

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  workflow_dispatch:
jobs:
  localize:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    strategy:
      matrix:
       lang: ["fr", "ro"] # List of languages for localization

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create translation branch for each language
        id: create-branch
        run: |
            LANG="${{ matrix.lang }}"
            UNIQUE_ID=$(date +%s) # Generate a unique ID using the current timestamp
            BRANCH_NAME="translation-${LANG}-${UNIQUE_ID}"

            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'

            # Create a new branch for the translation
            git checkout -b "$BRANCH_NAME"

            # Find new or modified files in the docs folder
            new_files=$(git diff --name-only HEAD^ HEAD -- 'docs/*')

            # Check if there are new or modified files
            if [ -z "$new_files" ]; then
            echo "No new or modified files found."
            exit 0 # Exit gracefully
            fi

            # Copy new or modified files to the localization folder for the specific language
            while IFS= read -r file; do
            relative_path=${file#docs/}
            destination_dir="i18n/${LANG}/docusaurus-plugin-content-docs-current/$(dirname "$relative_path")"

            # Create the destination directory if it doesn't exist
            mkdir -p "$destination_dir"

            # Copy the file to the localization folder
            if [ -f "$file" ]; then # Check if the file exists
                cp "$file" "$destination_dir/"
            else
                echo "Warning: File '$file' does not exist."
            fi
            done <<< "$new_files"

            # Check if there are any changes to commit
            if [ -n "$(git status --porcelain)" ]; then
            git add i18n/
            git commit -m "Add new or modified files for translation to ${LANG} branch"
            git push --set-upstream origin "$BRANCH_NAME"
            else
            echo "No new or modified files to commit."
            fi


      - name: Insert language code at the beginning of new files
        run: |
            LANG="${{ matrix.lang }}"
            # Find all new or modified files in the localization folder
            git diff --name-only HEAD^ HEAD -- "i18n/${LANG}/docusaurus-plugin-content-docs-current/**/*.md" | while IFS= read -r file; do
            # Check if the file exists
            if [ -f "$file" ]; then
                # Prepend the language code at the beginning of each file
                temp_file=$(mktemp) # Create a unique temporary file
                echo "${LANG}" | cat - "$file" > "$temp_file" && mv "$temp_file" "$file"
            else
                echo "Warning: File '$file' does not exist."
            fi
            done
        
            # Check if there are any changes to commit
            if [ -n "$(git status --porcelain)" ]; then
            git add i18n/
            git commit -m "Inserted language code for locale-${{ matrix.lang }}"
            git push origin $BRANCH_NAME
            else
            echo "No new or modified files to commit after inserting language code."
            fi

      - name: Create Pull Request for translation
        if: ${{ steps.create-branch.outputs.branch-name }}
        uses: peter-evans/create-pull-request@v5
        with:
          branch: $BRANCH_NAME # Source branch for the PR
          base: locale-${{ matrix.lang }} # Target branch for the PR
          title: "Automated Translation Update for ${{ matrix.lang }} - ${UNIQUE_ID}"
          body: "This PR contains automated modifications for the ${{ matrix.lang }} language and needs to be reviewed."
          #team-reviewers: "locale-${{ matrix.lang }}" # Request review from the language-specific team